module.exports = {
  up: `CREATE TABLE IF NOT EXISTS contas (
    conta_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(250) NOT NULL,
    apelido VARCHAR(250) NOT NULL,
    sexo ENUM('M', 'F') NOT NULL,
    email VARCHAR(250) NULL,
    telefone VARCHAR(20) NULL,
    senha VARCHAR(250) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ) ENGINE=InnoDB`,

  down: `DROP TABLE IF EXISTS contas`
};
